# -*- coding: utf-8 -*-
"""pandas-titanic-08-04-2023 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCPUAie40pWFIp_vzZe8s8bWU_ZsbtdQ
"""

import pandas as pd
import numpy as np
pd.__version__
pd.set_option("display.max_columns",100)

titanic = pd.read_csv("train.csv")

len(titanic)

titanic.head()

titanic.tail()

titanic.nunique()

titanic.drop(["PassengerId", "Name","Ticket"],axis = 1,inplace = True)

titanic.head()

gender_pivot = pd.pivot_table(data = titanic,index = ["Sex"],aggfunc = np.sum)
gender_pivot

class_pivot = pd.pivot_table(data = titanic,index = ["Sex","Pclass"],aggfunc = np.sum)
class_pivot

class_pivot = pd.pivot_table(data = titanic,index = ["Sex","Survived"],aggfunc = np.sum)
class_pivot

class_pivot = pd.pivot_table(data = titanic,index = ["Sex"],aggfunc = np.sum)
class_pivot

class_pivot = pd.pivot_table(data = titanic,index = ["Sex","Pclass"],values = ["Age"],aggfunc = np.mean)
class_pivot

class_pivot = pd.pivot_table(data = titanic,index = ["Sex"],values = ["Survived"],columns = ["Pclass"],aggfunc = np.sum)
class_pivot

